name: Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Déploie uniquement à partir de la branche main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du dépôt
      - uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build du projet
      - name: Build
        run: npm run build

      # 5️⃣ Déployer avec gh-pages
      - name: Deploy
        run: npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
